trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g yarn
      yarn install
      yarn build
    displayName: 'Yarn install and build'