trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g yarn
      yarn install
      yarn build
    displayName: 'Yarn install and build'

  - script: |
      mkdir -p ~/.ssh
      ssh-keyscan -H 20.11.243.20 >> ~/.ssh/known_hosts
      chmod 600 $(Build.SourcesDirectory)/azflowmvp_key.pem
      scp -i $(Build.SourcesDirectory)/azflowmvp_key.pem -r ./dist azureuser@20.11.243.20:/home/azureuser
    #      ssh -i $(Build.SourcesDirectory)/azflowmvp_key.pem azureuser@20.11.243.20<< 'EOF'
    #        sudo systemctl restart nginx
    #      EOF
    displayName: 'Deploy to MVP VM'